name: firestore_service_interface
description: An interface for a Firestore service for Flutter apps and Dart servers, providing a common interface for different implementations.
version: 0.0.0-a1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  json_utils:
    git: https://github.com/enspyrco/json_utils

dev_dependencies:
  enspyr_lints:
    git: https://github.com/enspyrco/enspyr_lints
  test: ^1.24.3